### ISSUE TITLE
Tracking issue for missing tests and corner cases

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-lang#465]
The test suite in this repo is extraordinarily useful and quite extensive. @singpolyma has also been doing an awesome job recently of adding a lot of unit tests (thanks !).
I thought it would be useful to have a central issue where we list which bits of the spec are or aren't fully tested, and corner cases of the semantics that aren't resolved one way or another yet.

I have two main goals with this: have unit tests for everything to help new implementors, and maximize test coverage for robustness. Another benefit of unit tests is that we're less likely to forget adding tests for every new feature.
I used a coverage tool to find missing corner cases with my implementation, so YMMV. If anyone else has coverage data to contribute, that would be awesome.

Feel free to edit this list to add entries or edit existing ones.

- [ ] parser
    - [ ] success unit tests
    - [ ] failure unit tests
    - [ ] Unions variants without type
    - [ ] `Some x`
    - [ ] `None`
    - [ ] `Kind`
    - [ ] We currently allow `Some x y z`. Decide what we want and test it.
    - [ ] We currently allow `True@2`. Decide what we want and test it.
- [ ] import
    - [ ] success unit tests
    - [ ] failures unit tests
- [ ] typecheck
    - [x] success unit tests
    - [ ] failures unit tests
    - [ ] interesting equivalence cases, like alpha-equivalence
    - [ ] variable shadowing, like `\(x: Type) -> \(x: x) -> x`
- [ ] normalization
    - [x] unit tests
    - [ ] interesting equivalence cases, like `if x then NaN else NaN`
    - [ ] variable shadowing, like `\(x: Type) -> \(x: x) -> x`
    - [ ] `merge {} <x = y>`
    - [ ] `{x = y}.z`
- [x] alpha-normalization
    - [ ] unit tests
        - [x] lambda
        - [x] forall
        - [ ] let
    - [ ] variable shadowing, like `\(x: Type) -> \(x: x) -> x`
- [ ] binary (binary and parser success tests will probably be shared)
    - [ ] encoding/decoding success unit tests
    - [ ] decoding failures unit tests
    - [ ] variable named `_`
    - [ ] `\(_: x) -> y`
    - [ ] `Some x`
    - [ ] `-1`
    - [ ] `../path`
    - [ ] variable named as a quoted builtin like `` `Bool` `` https://github.com/dhall-lang/dhall-lang/issues/462
- [x] hash
    - [x] unit tests

**Comment by Gabriel439** [comment]
The Haskell project also has a coverage report it generates (although you have to build it locally for the links to highlighted source code to work): https://hydra.dhall-lang.org/job/dhall-haskell/master/coverage-dhall/latest/download/1/hpc_index.html

Once I update the Haskell package to run the latest set of tests I can report back with anything else that I find

**Comment by f-f** [comment]
And here is the coverage report for `dhall-clj`'s master branch: https://coveralls.io/github/f-f/dhall-clj?branch=master

I'm in the process of catching up on dhall-lang's master, so the new test suites are still missing

**Comment by philandstuff** [comment]
Something I noticed today: the import unit tests don't have a test for *successfully* importing from an environment variable. I guess that's hard without requiring the test harness to set up the environment variable as expected.

**Comment by Nadrieril** [comment]
I checked quite a few boxes thanks to https://github.com/dhall-lang/dhall-lang/pull/523 :tada:

**Comment by sjakobi** [comment]
> The Haskell project also has a coverage report it generates (although you have to build it locally for the links to highlighted source code to work): https://hydra.dhall-lang.org/job/dhall-haskell/master/coverage-dhall/latest/download/1/hpc_index.html

@Gabriel439  The links for the per-module reports don't work. Do you know how to fix that?

**Comment by Gabriel439** [comment]
@sjakobi: Unfortunately, I do not know how to fix it.  You have to run the coverage check locally
